== フォーム

フォームに入力してGitHub API発行

++++

<form id="custom_form" target="dummy_send_target">
    <div class="item">
      <label for="emailAddress">メールアドレス</label>
      <input id="emailAddress" type="email" name="emailAddress" placeholder="example@mail.com" required></input>
    </div>
    <div class="item">
      <label for="question_title">質問タイトル</label>
      <input id="question_title" type="text" name="question_title" placeholder="質問タイトル" required></input>
    </div>
    <div>
      <label for="question_detail">質問内容</label>
      <textarea id="question_detail" name="question_detail" placeholder="コメントお願いします"></textarea>
    </div>
    <!--
    <div class="item">
      <button type="submit">送信</button>
    </div>
    -->
    <input type="submit" name="btn_submit" value="送信">
    <input type="hidden" name="form_session" value="ta9galkjlsGJ==">
</form>
<p id="words_of_thanks">
    送信されました
</p>
<style>
  table {
    border-collapse: collapse;
  }

  p {
    font-size: 16px;
    font-weight: bold;
    text-align: center;
    margin: 60px auto 40px;
  }

  input[type="submit"],
  input[type="text"],
  input[type="email"],
  select,
  textarea,
  button {
    -moz-appearance: none;
    -webkit-appearance: none;
    -webkit-box-shadow: none;
    box-shadow: none;
    outline: none;
    border: none;
  }

  input[type="text"],
  input[type="email"],
  textarea {
    background: #f8f8f8;
    display: block;
    font-size: 16px;
    padding: 12px 15px;
    width: 480px;
    transition: 0.8s;
    border-radius: 0;
  }

  input[type="text"]:focus,
  textarea:focus {
    background: #e9f5fb;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
  }

  textarea[name="content"] {
    display: inline-block;
    width: 100%;
    height: 200px;
  }

  input::placeholder,
  textarea::placeholder {
    color: #ccc;
  }

  ::-webkit-input-placeholder {
    color: #ccc;
    opacity: 1;
  }

  ::-moz-placeholder {
    color: #ccc;
    opacity: 1;
  }

  :-ms-input-placeholder {
    color: #ccc;
    opacity: 1;
  }

  .form-table {
    width: 100%;
  }

  .form-table th,
  .form-table td {
    display: block;
    width: 100%;
    border-bottom: none;
  }

  .form-table th {
    background: #ffecea;
    padding-left: 50px;
    position: relative;
    text-align: left;
    width: 300px;
  }

  #words_of_thanks {
      display: none;
  }
</style>
<script type="module">
  import { Octokit } from "https://cdn.skypack.dev/@octokit/core";

  function getArgs(e) {
    // path
    const path_name = location.pathname;

    // mail
    const input_emailAddress = document.querySelector("input[name=emailAddress]");
    const mail_val = input_emailAddress.value;

    // title
    const input_question_title = document.querySelector("input[name=question_title]");
    const title_val = input_question_title.value;

    // detail
    if (document.querySelector("textarea").value != "") {
      var input_question_detail = document.querySelector("textarea");
      var textarea_val = input_question_detail.value;
    }
    else { //empty
      var textarea_val = "本文はありません";
    }

    return [path_name, mail_val, title_val, textarea_val] ;
  }

  const putIssue2GitHub = async function(args) {
    const [path_name, mail_val, title_val, body] = args

    // GitHub API instance
    const octokit = new Octokit({ auth: `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` });
    console.log(octokit)

    // debug
    window.alert(`入力値:\n\n`
                  + `path:\n ${path_name} \n`
                  + `mail address:\n ${mail_val} \n`
                  + `title:\n ${title_val} \n`
                  + `body:\n ${body}`) ;

    // create Issue
    const response = await octokit.request('POST /repos/{owner}/{repo}/issues', {
      owner: 'mattynao',
      repo: 'utterances_test',
      title: title_val,
      body: body
    })
    console.log(response)
  }

  var input_submit = document.querySelector("input[type=submit]");
  input_submit.addEventListener("click", function(e){

    // cancel
    e.preventDefault();

    //[path_name, mail_val, title_val, textarea_val]
    let args = getArgs(e) ;
    const [path_name, mail_val, title_val, textarea_val] = args ;

    const body = `#### 投稿者メールアドレス\n ${mail_val} \n\n`
                + `### 対象ページ\n ${path_name}\n\n`
                + `## 質問 \n ${textarea_val}`

    const args2git = [path_name, mail_val, title_val, body]
    putIssue2GitHub(args2git) ;

  });
</script>

++++
