== Googleフォーム

埋め込みフォームからGoogleフォームに入力

++++

  <form id="custom_form" target="dummy_send_target">
      <div class="item">
        <label for="emailAddress">メールアドレス</label>
        <input id="emailAddress" type="email" name="emailAddress" placeholder="example@mail.com" required></input>
      </div>

      <div class="item">
        <label for="title">質問</label>
        <input id="title" type="text" name="entry.1664715574" placeholder="質問の概要" required></input>
      </div>

      <div class="item">
        <label for="question">質問内容</label>
        <textarea id="question" name="entry.1035960842" cols="30" rows="10" placeholder="質問の詳細をお書きください"></textarea>
      </div>

      <div class="item">
        <input id="file_name" type="hidden" name="entry.593226274"></input>
      </div>

      <div class="item">
        <button type="submit">送信</button>
      </div>
  </form>
  <p id="words_of_thanks">
      送信されました
  </p>
  <style>
    table {
      border-collapse: collapse;
    }

    p {
      font-size: 16px;
      font-weight: bold;
      text-align: center;
      margin: 60px auto 40px;
    }

    input[type="submit"],
    input[type="text"],
    input[type="email"],
    select,
    textarea,
    button {
      -moz-appearance: none;
      -webkit-appearance: none;
      -webkit-box-shadow: none;
      box-shadow: none;
      outline: none;
      border: none;
    }

    input[type="text"],
    input[type="email"],
    textarea {
      background: #f8f8f8;
      display: block;
      font-size: 16px;
      padding: 12px 15px;
      width: 480px;
      transition: 0.8s;
      border-radius: 0;
    }

    input[type="text"]:focus,
    textarea:focus {
      background: #e9f5fb;
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
    }

    textarea[name="content"] {
      display: inline-block;
      width: 100%;
      height: 200px;
    }

    input::placeholder,
    textarea::placeholder {
      color: #ccc;
    }

    ::-webkit-input-placeholder {
      color: #ccc;
      opacity: 1;
    }

    ::-moz-placeholder {
      color: #ccc;
      opacity: 1;
    }

    :-ms-input-placeholder {
      color: #ccc;
      opacity: 1;
    }

    .form-table {
      width: 100%;
    }

    .form-table th,
    .form-table td {
      display: block;
      width: 100%;
      border-bottom: none;
    }

    .form-table th {
      background: #ffecea;
      padding-left: 50px;
      position: relative;
      text-align: left;
      width: 300px;
    }

    #words_of_thanks {
        display: none;
    }
  </style>
  <script>
      function get_textbox_value(name) {
          const element = document.querySelector(`input[type=text][name="${name}"]`);
          if(element.value) {
              return element.value;
          } else {
              return ""
          }
      }
      function get_email_value(name) {
          const element = document.querySelector(`input[type=email][name="${name}"]`);
          if(element.value) {
              return element.value;
          } else {
              return ""
          }
      }
      function get_textarea_value(name) {
          const element = document.querySelector(`textarea[name="${name}"]`);
          if(element.value) {
              return element.value;
          } else {
              return ""
          }
      }

      function ask_before_changing_page(event) {
          event.preventDefault();
          event.returnValue = "";
      }

      document.getElementById("custom_form").addEventListener("submit", function() {
          const dummy_send_target = document.createElement("iframe");
          dummy_send_target.style.display = "none";
          dummy_send_target.name = "dummy_send_target";
          document.getElementById("custom_form").appendChild(dummy_send_target);

          const form_iframe = document.createElement("iframe");
          form_iframe.src = encodeURI(`https://docs.google.com/forms/u/0/d/e/1FAIpQLSd8jktXNPJ8HiHzZRWLIsl5uICauyyRnZu61SwT7PhMqyk1XQ/formResponse?emailAddress=${get_email_value("emailAddress")}&entry.1664715574=${get_textbox_value("entry.1664715574")}&entry.593226274=${location.pathname}&submit=Submit`);
          //form_iframe.src = encodeURI(`https://docs.google.com/forms/u/0/d/e/1FAIpQLSd8jktXNPJ8HiHzZRWLIsl5uICauyyRnZu61SwT7PhMqyk1XQ/formResponse?emailAddress=${get_email_value("emailAddress")}&entry.1664715574=${get_textbox_value("entry.1664715574")}&entry.1035960842=${get_textarea_value("entry.1035960842")}&entry.593226274=${location.pathname}&submit=Submit`);

          form_iframe.style.display = "none";
          document.getElementById("custom_form").appendChild(form_iframe);

          form_iframe.addEventListener("load", function() {
              document.getElementById("custom_form").remove();
              document.getElementById("words_of_thanks").style.display = "block";
              window.removeEventListener("beforeunload", ask_before_changing_page, false);
          });
      });

      window.addEventListener("beforeunload", ask_before_changing_page);
  </script>

++++
